# -*- coding: utf-8 -*-
"""code_01_collatz3_shiftless_equivalence
"""

# Copyright (c) 2026 Hiroshi Harada
# Licensed under the MIT License.
# https://opensource.org/licenses/MIT
# Author: Hiroshi Harada
# Date: May 2, 2026


import csv
import math
import matplotlib.pyplot as plt

def get_non_3_part(n):
    """
    Return the non-3-multiple part of n by dividing out all factors of 3.
    This is essential for comparing the standard 3-adic Collatz sequence
    with the 3-adic Shiftless Collatz sequence.
    """
    if n == 0:
        return 0
    while n % 3 == 0:
        n //= 3
    return n


def valuation_3(n):
    """
    Return v such that 3^v divides n but 3^(v+1) does not.
    """
    if n == 0:
        return float("inf")
    v = 0
    while n % 3 == 0:
        n //= 3
        v += 1
    return v


def verify_equivalence_3adic(seed, csv_path="figure1.csv", png_path="figure1.png"):
    """
    Verify the mathematical identity between:

    1. Standard 3-adic Collatz:
       The sequence of non-3-multiples generated by repeatedly applying
       (4n - 1)/3 or (4n + 1)/3 based on n mod 3.

    2. Shiftless 3-adic Collatz:
       The sequence generated by n_{k+1} = 4n_k + c * 3^v,
       where 3^v is the weight of the lowest non-zero trit,
       c = -1 (if trit is 1) and c = +1 (if trit is 2).

    The non-3-part of the Shiftless trajectory must match the non-3-part
    of the standard trajectory at every step.

    Additionally:
    - Save the trajectory as CSV
    - Save a PNG plot of the non-3 parts
    """

    n_std = get_non_3_part(seed)  # Standard Collatz non-3 part
    n_sft = seed                  # Shiftless Collatz full value
    step = 0

    rows = []
    rows.append(["Step", "Standard_Non3", "Shiftless", "Shiftless_Non3", "Match"])

    print(f"Verification for 3-adic Seed: {seed}")
    print(f"{'Step':<5} | {'Standard (Non-3)':<18} | {'Shiftless':<25} | {'Non-3(Shiftless)':<18} | Match?")
    print("-" * 90)

    # Continue until Shiftless Collatz reaches a power of 3 (Jackpot)
    while True:

        # Jackpot check for Shiftless
        if get_non_3_part(n_sft) == 1:
            break

        # --- Standard 3-adic Collatz Step ---
        if n_std % 3 == 1:
            n_std = (4 * n_std - 1) // 3
        elif n_std % 3 == 2:
            n_std = (4 * n_std + 1) // 3

        n_std = get_non_3_part(n_std)

        # --- Shiftless 3-adic Collatz Step ---
        temp = n_sft
        v = valuation_3(temp)
        temp //= 3**v

        # NZT = 0 → Jackpot → break
        if temp == 1:
            break

        t = temp % 3
        c = -1 if t == 1 else 1
        weight = 3 ** v

        n_sft = 4 * n_sft + c * weight

        step += 1

        # Non-3 part of Shiftless value
        non_3_sft = get_non_3_part(n_sft)

        # Check equivalence
        match = (n_std == non_3_sft)

        print(f"{step:<5} | {n_std:<18} | {n_sft:<25} | {non_3_sft:<18} | {match}")

        rows.append([step, n_std, n_sft, non_3_sft, match])

        if not match:
            print("Mismatch detected. Stopping.")
            break

    print("-" * 90)

    # Compute Jackpot exponent
    power = valuation_3(n_sft)
    print(f"Verification Successful. Total steps to Jackpot: {step}")
    print(f"Final Jackpot Value: 3^{power}")

    # --- Save CSV ---
    with open(csv_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerows(rows)
    print(f"CSV saved to: {csv_path}")

    # --- Save PNG plot ---
    steps = [row[0] for row in rows[1:]]
    std_vals = [row[1] for row in rows[1:]]
    sft_vals = [row[3] for row in rows[1:]]

    plt.figure(figsize=(10, 6))
    plt.plot(steps, std_vals, label="Standard 3-adic (Non-3 part)", marker="o")
    plt.plot(steps, sft_vals, label="Shiftless (Non-3 part)", marker="x")
    plt.xlabel("Step")
    plt.ylabel("Non-3 Part")
    plt.title("Figure 1: Equivalence of Standard and Shiftless 3-adic Collatz")
    plt.legend()
    plt.grid(True)
    plt.savefig(png_path, dpi=200)
    plt.close()

    print(f"PNG saved to: {png_path}")


if __name__ == "__main__":
    # Recommended seeds: 28, 20737, etc.
    verify_equivalence_3adic(28)

